### ISSUE TITLE
Request help, node reported  error

### ISSUE THREAD

**Issue by aimarxjg** [meap158/ComfyUI-Prompt-Expansion#1]
![9080857](https://github.com/meap158/ComfyUI-Prompt-Expansion/assets/132532636/be5e05c6-8dd4-4ee5-8b1f-ea31fc8a13e9)

Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'find')
TypeError: Cannot read properties of undefined (reading 'find')
    at nodeType.onConfigure (http://127.0.0.1:8188/extensions/core/widgetInputs.js:141:30)
    at nodeType.onConfigure (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/locking.js:178:17)
    at LGraphNode.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2549:18)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2240:26)
    at LGraph.configure (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/pysssss/CustomScripts/snapToGrid.js:53:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1219:15)
    at ComfyApp.setup (http://127.0.0.1:8188/scripts/app.js:1083:10)
    at async http://127.0.0.1:8188/:13:4
This may be due to the following script:
/extensions/core/widgetInputs.js

**Comment by kubilaykilinc** [comment]
same too

**Comment by meap158** [comment]
I'm not sure what the problem is here. It seems to indicate some issue with the custom node 'CustomScripts.' I'd suggest you  guys update ComfyUI and disable that node temporarily to see if it works

**Comment by MatMarrr** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
vinvilla, @kaihei777, @NasirNobin, @paulgb, @stolho, @bhalothia, @llagos, @brianfrantz, @acangiani, @dmlogv, @TheFynx, @andreparrish, @kjalnes, @w15ard, @bfulton, @emilioinfinity, @wkunker, @iwasakishuto, @mikeputnam, @Clinberg, @yatmsu, @geosimcos, @nickolay-loginov-clearscale, @PedroCarrasco82, @cassens, @Syuq, @zuyu, @marcokorb, @joehmn, @KilJaeeun, @amilenkovic, @asmaps, @Kezzo, @natebuhar, @dtimberlake, @PaulFurtado, @arpat, @ethnzhng, @clavisinsight, @minhluuquang, @Mohasemi, @GProst, @krishnabhashkarjha, @micropack, @seckinsen, @agergo, @felipeschossler, @aes512, @SebastianElvis, @panozzajakaralar, @denysvitali, @TomoyaIshida, @shuixingzai, @Daeinar, @whatshotcodes, @wtcross, @Nacriema, @xanos3000, @dmitriyK1, @elkhan, @korjjj, @1198560751, @iamjarvo, @srinitude, @maruLab, @hachre, @thereisnosun, @rob-robinson, @leandrost, @issei-m, @mozamimy, @shouse, @princekwes, @theory-code, @luankevinferreira, @Kamalabot, @0x1bitcrack3r, @Upasanadhameliya, @morjacobi, @tjhartmann, @justinharringa, @SuryaElite, @SeppPenner, @ivankovnatsky, @bob2827, @Thilak-KN, @loevlie, @z0ph, @Pruthvi2121, @koji-yamauchi, @bencooling, @cmackenzie1, @AbdulmalikGiwa, @discdiver, @amazoncathan, @sffej, @kohane27, @chahatagarwal, @d3fault0mlvnds, @lewiswu, @mikeadmire, @raydigitallife, @hikarika, @wang-nets, @rodrigodma, @hippotized, @ozgio, @jnonino, @chris-schmitz, @DManavi, @hawk27x, @quanpower, @ZHAODayou, @laurentgoudet, @azygmunciak, @macrism, @dreikanter, @muriloviana, @Maiveasna, @xmarcos, @shankys, @tuksik, @bamboo-vn, @yuxiang-zhang, @studiomaestro, @jimdial-aws, @mikoim, @toomuat, @alexysbike, @kidculli, @KeshavJha, @Lunatix01, @nk2164, @gionn, @arturhoo, @annahung31, @Priyaaaaaaaaaaaaaaaa, @luissquall, @nullx5, @cassandrale179, @craigdmckenna, @kikeex, @gorsejnsve, @planet, @rasaka, @JBed, @choweiyuan, @Nabeelperson
